### ISSUE TITLE
Issue at the "Organizing pipeline" step

### ISSUE THREAD

**Issue by brendanyoungArzeda** [octantbio/octopus3#1]
Hi there, 

I'm trying to use Octopus3.0 on a recent sequencing run and running into the same issue when running both the run-octopus-analysis.sh script and when manually entering 'make denovo' in the docker.

After loading in the sequencing data and running the pipeline I get the following error:

./run-octopus-analysis.sh -q $(pwd)/GDABQ-460 -d octopus3:release
Automated OCTOPUS computational pipeline started!
Linking data . . .
No valid input fasta directory provided. Performing de-novo alignment only.
Running de-novo alignment . . .
Running docker image "octopus3:release"
Organizing pipeline/GDABQ-460
mv: cannot move 'pipeline/GDABQ-460/data//OCTOPUS-01_R1.fastq.gz' to 'pipeline/GDABQ460/data//OCTOPUS01_R1.fastq.gz': No such file or directory
make: *** [Makefile:36: pipeline/GDABQ-460/organize] Error 1
Exiting pipeline prematurely.

GDABQ-460 is where the sequencing files are housed and the structure is:

GDABQ-460 > SampleSheet.csv Alignment_1 > 20230721 > Fastq > *.fastq.gz

Which works (as far as I can tell) when I make the symlinks using link-data.py

So I don't know what's going wrong at the pipeline step, any help would be great!

**Comment by brendanyoungArzeda** [comment]
Ok, so I realized today that the '-' in GDABQ-460 was likely causing issues and resolved that, to immediately run into another similar issue with my source files:

./run-octopus-analysis.sh -q $(pwd)/GDABQ460 -d octopus3:release
Automated OCTOPUS computational pipeline started!
Linking data . . .
No valid input fasta directory provided. Performing de-novo alignment only.
Running de-novo alignment . . .
Running docker image "octopus3:release"
Organizing pipeline/GDABQ460
**mv: 'pipeline/GDABQ460/data//Undetermined_R1.fastq.gz' and 'pipeline/GDABQ460/data//Undetermined_R1.fastq.gz' are the same file**
make: *** [Makefile:36: pipeline/GDABQ460/organize] Error 1
Exiting pipeline prematurely.

That file is indeed the same file as itself, I'm not sure what is wrong here? Is this potentially another filepath issue, or something else? Any guidance into what's going on at this step would be great.

**Comment by bryanliujiang** [comment]
Hi @brendanyoungArzeda! My sincere apologies for not seeing this sooner.

What I immediately see is that the pipeline was not able to properly extract the plate names from the `Sample_Plate` column in the SampleSheet.csv [Data] section. I would recommend reading the last few points of the [Sequencing Step of the bench protocol page](https://github.com/octantbio/octopus3/blob/main/docs/Bench-Protocol.md#3-library-quantification-and-sequencing-setup) for more details and an example of a sample sheet layout compatible with the analysis pipeline we provide. 

Did you have this in your sample sheet? The pipeline as it is assumes such a column exists. Even if there were just one plate, you would need to make sure each sample still has a Sample_Plate associated with it in the sample sheet. Might want to clear out the `pipeline/` directory of any earlier `pipeline/GDABQ460` runs just in case before rerunning with any updated sample sheet.
Since I suspect the sample sheet parsing to be the issue, it should also be safe to have your run with the '-' in its name, i.e. GDABQ-460 as the name should work just fine.

If you haven't already and assuming you cloned this repo, see if the test data works, as it includes test data and compatible sample sheet. Simply follow the [Method 1 steps](https://github.com/octantbio/octopus3/blob/main/docs/Running-the-Analysis-Pipeline.md#method-1-run-octopus-analysissh) and copy in the line of code in step 2 exactly.

Thanks for your patience and trying out our provided pipeline! That Sample_Plate detail was not obvious with how hidden it was in the documentation, thanks for reaching out. Will try to make it more clear in the future.

**Comment by brendanyoungArzeda** [comment]
@bryanliujiang Oh thank you so much! That saved my work, the samplesheet was definitely missing the Sample_Plate column, I was able to complete the de novo analysis pipeline!

**Comment by bryanliujiang** [comment]
Yay! Glad I was of help!
